### ISSUE TITLE
Auto Rip all Gems

### ISSUE THREAD

**Issue by reidcooper** [gurgeous/bust-a-gem#18]
Would like to auto-rip all gems that are provided by the `bustagem.cmd.bundle` (`bundle show --paths`). The plugin only rips gem that are whitelisted in `bustagem.gems`.

Do you think it would be possible to just change the `rip` command to be something like this:

```
ripper-tags -f TAGSSSSSSS -R --force --extra=q $(pwd) $(bundle show --paths)
```

(pseudo code)

**Comment by gurgeous** [comment]
Hey Reid. You might be able to make that work by customizing the `bustagem.cmd.rip` setting. It defaults to `ripper-tags -f TAGS -R --force --extra=q`, but it might work if you set it to the above. Try it and report back!

**Comment by reidcooper** [comment]
@gurgeous So I went back and gave this a shot.

Deleted `TAGS` and adjusted the `rip` command to: `ripper-tags -f TAGS -R --force --extra=q $(bundle show --paths)`

The resulting `TAGS` seemed to be successful as far as I can tell.

**Comment by gurgeous** [comment]
Great, thanks!

**Comment by vfonic** [comment]
I was getting a warning from the extension that I passed in `"bustagem.gems"` a gem name that's not in the project. This is true, because I have only one global user settings (no workspace settings). I don't want to have to create workspace settings for every ruby project I work on. So instead of that, with a little help from this issue, I removed `"bustagem.gems"` setting and instead added this:
`"bustagem.cmd.rip": "ripper-tags -f TAGS -R --force --extra=q $(bundle show --paths | grep -E \"(activeadmin|shopify|webflow)\")",`

This "rips" only those few gems it matches and doesn't give me warnings if none of the gem names match.

Thanks for the idea @reidcooper and @gurgeous!

**Comment by reidcooper** [comment]
@vfonic  oh that's a great idea! Thank you for sharing!

**Comment by synth** [comment]
Glad I found this, this is super helpful! Any reason to not include this in the main README? Autoripping all gems seems like a sensible default or at very least a suggested configuration in the README. WDYT?

**Comment by gurgeous** [comment]
Great idea, done! thanks guys

**Comment by Nowaker** [comment]
I wanted to bust all gems, but getting an error:

```
% ripper-tags -f TAGS -R --force --extra=q $(bundle show --paths)
/home/nowaker/.rvm/gems/ruby-3.3.0/gems/ripper-tags-1.0.1/lib/ripper-tags/emacs_formatter.rb:72:in `fetch': key not found: :name (KeyError)
        from /home/nowaker/.rvm/gems/ruby-3.3.0/gems/ripper-tags-1.0.1/lib/ripper-tags/emacs_formatter.rb:72:in `format'
        from /home/nowaker/.rvm/gems/ruby-3.3.0/gems/ripper-tags-1.0.1/lib/ripper-tags/emacs_formatter.rb:37:in `write'
        from /home/nowaker/.rvm/gems/ruby-3.3.0/gems/ripper-tags-1.0.1/lib/ripper-tags.rb:237:in `block (2 levels) in run'
        from /home/nowaker/.rvm/gems/ruby-3.3.0/gems/ripper-tags-1.0.1/lib/ripper-tags/data_reader.rb:160:in `block (2 levels) in each_tag'
        from /home/nowaker/.rvm/gems/ruby-3.3.0/gems/ripper-tags-1.0.1/lib/ripper-tags/data_reader.rb:159:in `each'
        from /home/nowaker/.rvm/gems/ruby-3.3.0/gems/ripper-tags-1.0.1/lib/ripper-tags/data_reader.rb:159:in `block in each_tag'
        from /home/nowaker/.rvm/gems/ruby-3.3.0/gems/ripper-tags-1.0.1/lib/ripper-tags/data_reader.rb:66:in `resolve_file'
        from /home/nowaker/.rvm/gems/ruby-3.3.0/gems/ripper-tags-1.0.1/lib/ripper-tags/data_reader.rb:61:in `block in resolve_file'
        from /home/nowaker/.rvm/gems/ruby-3.3.0/gems/ripper-tags-1.0.1/lib/ripper-tags/data_reader.rb:86:in `block in each_in_directory'
        from /home/nowaker/.rvm/gems/ruby-3.3.0/gems/ripper-tags-1.0.1/lib/ripper-tags/data_reader.rb:84:in `each'
        from /home/nowaker/.rvm/gems/ruby-3.3.0/gems/ripper-tags-1.0.1/lib/ripper-tags/data_reader.rb:84:in `each_in_directory'
        from /home/nowaker/.rvm/gems/ruby-3.3.0/gems/ripper-tags-1.0.1/lib/ripper-tags/data_reader.rb:59:in `resolve_file'
        from /home/nowaker/.rvm/gems/ruby-3.3.0/gems/ripper-tags-1.0.1/lib/ripper-tags/data_reader.rb:61:in `block in resolve_file'
        from /home/nowaker/.rvm/gems/ruby-3.3.0/gems/ripper-tags-1.0.1/lib/ripper-tags/data_reader.rb:86:in `block in each_in_directory'
        from /home/nowaker/.rvm/gems/ruby-3.3.0/gems/ripper-tags-1.0.1/lib/ripper-tags/data_reader.rb:84:in `each'
        from /home/nowaker/.rvm/gems/ruby-3.3.0/gems/ripper-tags-1.0.1/lib/ripper-tags/data_reader.rb:84:in `each_in_directory'
        from /home/nowaker/.rvm/gems/ruby-3.3.0/gems/ripper-tags-1.0.1/lib/ripper-tags/data_reader.rb:59:in `resolve_file'
        from /home/nowaker/.rvm/gems/ruby-3.3.0/gems/ripper-tags-1.0.1/lib/ripper-tags/data_reader.rb:61:in `block in resolve_file'
        from /home/nowaker/.rvm/gems/ruby-3.3.0/gems/ripper-tags-1.0.1/lib/ripper-tags/data_reader.rb:86:in `block in each_in_directory'
        from /home/nowaker/.rvm/gems/ruby-3.3.0/gems/ripper-tags-1.0.1/lib/ripper-tags/data_reader.rb:84:in `each'
        from /home/nowaker/.rvm/gems/ruby-3.3.0/gems/ripper-tags-1.0.1/lib/ripper-tags/data_reader.rb:84:in `each_in_directory'
        from /home/nowaker/.rvm/gems/ruby-3.3.0/gems/ripper-tags-1.0.1/lib/ripper-tags/data_reader.rb:59:in `resolve_file'
        from /home/nowaker/.rvm/gems/ruby-3.3.0/gems/ripper-tags-1.0.1/lib/ripper-tags/data_reader.rb:99:in `block in each_file'
        from /home/nowaker/.rvm/gems/ruby-3.3.0/gems/ripper-tags-1.0.1/lib/ripper-tags/data_reader.rb:112:in `each'
        from /home/nowaker/.rvm/gems/ruby-3.3.0/gems/ripper-tags-1.0.1/lib/ripper-tags/data_reader.rb:112:in `each_input_file'
        from /home/nowaker/.rvm/gems/ruby-3.3.0/gems/ripper-tags-1.0.1/lib/ripper-tags/data_reader.rb:98:in `each_file'
        from /home/nowaker/.rvm/gems/ruby-3.3.0/gems/ripper-tags-1.0.1/lib/ripper-tags/data_reader.rb:150:in `each_tag'
        from /home/nowaker/.rvm/gems/ruby-3.3.0/gems/ripper-tags-1.0.1/lib/ripper-tags.rb:236:in `block in run'
        from /home/nowaker/.rvm/gems/ruby-3.3.0/gems/ripper-tags-1.0.1/lib/ripper-tags/emacs_formatter.rb:27:in `block in with_output'
        from /home/nowaker/.rvm/gems/ruby-3.3.0/gems/ripper-tags-1.0.1/lib/ripper-tags/default_formatter.rb:53:in `block in with_output'
        from /home/nowaker/.rvm/gems/ruby-3.3.0/gems/ripper-tags-1.0.1/lib/ripper-tags/default_formatter.rb:52:in `open'
        from /home/nowaker/.rvm/gems/ruby-3.3.0/gems/ripper-tags-1.0.1/lib/ripper-tags/default_formatter.rb:52:in `with_output'
        from /home/nowaker/.rvm/gems/ruby-3.3.0/gems/ripper-tags-1.0.1/lib/ripper-tags/emacs_formatter.rb:25:in `with_output'
        from /home/nowaker/.rvm/gems/ruby-3.3.0/gems/ripper-tags-1.0.1/lib/ripper-tags.rb:235:in `run'
        from /home/nowaker/.rvm/gems/ruby-3.3.0/gems/ripper-tags-1.0.1/lib/ripper-tags.rb:206:in `call'
        from /home/nowaker/.rvm/gems/ruby-3.3.0/gems/ripper-tags-1.0.1/lib/ripper-tags.rb:206:in `block in process_args'
        from /home/nowaker/.rvm/gems/ruby-3.3.0/gems/ripper-tags-1.0.1/lib/ripper-tags.rb:182:in `block in option_parser'
        from /home/nowaker/.rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/optparse.rb:1153:in `initialize'
        from /home/nowaker/.rvm/gems/ruby-3.3.0/gems/ripper-tags-1.0.1/lib/ripper-tags.rb:84:in `new'
        from /home/nowaker/.rvm/gems/ruby-3.3.0/gems/ripper-tags-1.0.1/lib/ripper-tags.rb:84:in `option_parser'
        from /home/nowaker/.rvm/gems/ruby-3.3.0/gems/ripper-tags-1.0.1/lib/ripper-tags.rb:187:in `process_args'
        from /home/nowaker/.rvm/gems/ruby-3.3.0/gems/ripper-tags-1.0.1/bin/ripper-tags:15:in `<top (required)>'
        from /home/nowaker/.rvm/gems/ruby-3.3.0/bin/ripper-tags:25:in `load'
        from /home/nowaker/.rvm/gems/ruby-3.3.0/bin/ripper-tags:25:in `<main>'
        from /home/nowaker/.rvm/gems/ruby-3.3.0/bin/ruby_executable_hooks:22:in `eval'
        from /home/nowaker/.rvm/gems/ruby-3.3.0/bin/ruby_executable_hooks:22:in `<main>'
```

I reported it to https://github.com/tmm1/ripper-tags/issues/115

Meanwhile, here's my modified command to skip these problematic gems that ripper-tags chokes on: `ripper-tags -f TAGS -R --force --exclude '*/airbrussh/colors.rb' --exclude '*/lib/net/ssh/authentication/pageant.rb' --exclude '*/mail-2.8.0.rc1' --extra=q $(bundle show --paths)`

`airbrussh` and `net-ssh` specifically. I also included `mail` because it takes forever to rip it.

**Comment by gurgeous** [comment]
ripper-tags is a great project, I hope they fix it.  Sorry that was so annoying to track down...
